### ISSUE TITLE
Error selecting date field - `invalid selector for date: a.rounded-md`

### ISSUE THREAD

**Issue by trustin** [wezm/rsspls#24]
Given the following configuration:

```toml
[rsspls]
output = "/tmp"

[[feed]]
title = "DeepLearning.ai"
filename = "deeplearning-ai.rss"

[feed.config]
url = "https://www.deeplearning.ai/the-batch/"
item = "article"
heading = "h2"
link = "a.absolute"

[feed.config.date]
selector = "a.rounded-md" # or "a.relative"
type = "Date"
format = "[month repr:short] [day], [year]"
```

It always fails with the following error:

```
 INFO  rsspls > processing https://www.deeplearning.ai/the-batch/
 ERROR rsspls > error processing feed for https://www.deeplearning.ai/the-batch/

Caused by:
    invalid selector for date: a.rounded-md
```

I'm pretty sure `document.querySelectorAll("article a.rounded-md")` returns the date elements in my browser. What could be the problem?

As a workaround, I used `selector = "div a"`, which seems to work, but with some warnings:

```
 WARN  rsspls > unable to parse date ''
 WARN  rsspls > unable to parse date ''
 WARN  rsspls > unable to parse date ''
```

**Comment by wezm** [comment]
Wow the markup of that page is the antithesis of semantic HTML. I think the issue is that the `article` selector is too broad. It's selecting items in the "Popular Articles" section, which don't have an element matching `a.rounded-md`.

`article.h-full` looks like it will select the big article as well as the smaller ones following it.
